//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchulteGrid {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchulteGrid.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于游戏 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 神棍工作室 的本地化字符串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系作者 的本地化字符串。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏说明：
        ///“舒尔特方格”不但可以简单测量注意力水平，而且是很好的训练方法。
        ///它是心理咨询师进行心理治疗时常用的基本方法。
        ///培养注意力集中、分配、控制能力;
        ///提高视觉的稳定性、辨别力、定向搜索能力。
        ///游戏规则：
        ///按1——25的顺序依次点其位置。 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本游戏创意来源于网络，由神棍工作室制作完成。
        ///请尊重个人劳动成果，切勿盗用。 的本地化字符串。
        /// </summary>
        public static string Explain {
            get {
                return ResourceManager.GetString("Explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在游戏，是否退出？ 的本地化字符串。
        /// </summary>
        public static string MessageBoxExit {
            get {
                return ResourceManager.GetString("MessageBoxExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 询问 的本地化字符串。
        /// </summary>
        public static string MessageBoxQuestion {
            get {
                return ResourceManager.GetString("MessageBoxQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否重新开始？ 的本地化字符串。
        /// </summary>
        public static string MessageBoxRestart {
            get {
                return ResourceManager.GetString("MessageBoxRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以 7—12 岁年龄组为例，能达到26&apos;&apos;以上为优秀，学习成绩应是名列前茅， 42&apos;&apos;属于中等水平，班级排名会在中游或偏下， 50&apos;&apos;则问题较大，考试会出现不及格现象。&amp;#13;18 岁及以上成年人最好可达到 8&apos;&apos;的水平， 25&apos;&apos;为下等水平。 的本地化字符串。
        /// </summary>
        public static string Over {
            get {
                return ResourceManager.GetString("Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 舒尔特方格 的本地化字符串。
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再来一次 的本地化字符串。
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评价与分享 的本地化字符串。
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始游戏 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
    }
}
